#!/bin/bash



##############
#this script output the node health
#
#Version:v1
##############
set -x #debug mode
set -e #exit the script when there is an error
set -o pipefail


df -h

free -g

nproc 

ps -ef | grep nginx | awk -F " " '{print $2}'

curl https://raw.githubusercontent.com/iam-veeramalla/sandbox/main/log/dummylog01122022.log | grep ERROR

#wget is similar to curl but here the output can be stored in a file

#sudo su - is used to get to root user
